---

- name: Creating users
  user: >
    name={{ item.name }}
    comment="{{ item.comment }}"
    group={{ item.group }}
    groups={{ item.groups }}
    shell={{ item.shell }}
  with_items: users
  tags:
    - system
    - users

- name: Setting user's home permission
  file: >
    dest=/home/{{ item.name }}
    owner={{ item.name }}
    mode=0755
  with_items: users
  tags:
    - system
    - users

- name: Adding ssh keys
  template: >
    src=home-user-ssh-id_rsa.j2
    dest=/home/{{ item.name }}/.ssh/id_rsa
    owner={{ item.name }}
    mode=0600
  with_items: users
  tags:
    - system
    - users

- name: Adding authorized keys
  authorized_key: >
    user={{ item.0.name }}
    key="{{ item.1 }}"
  with_subelements:
    - users
    - authorized_keys
  tags:
    - system
    - users
