---

- name: Adding users
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid|default(omit) }}"
    home: "{{ item.home|default(users_home ~ '/' ~ item.username ) }}"
    comment: "{{ item.name|default(omit) }}"
    system: "{{ item.system|default(omit) }}"
    generate_ssh_key: "{{ item.ssh_key_generate|default(omit) }}"
    group: "{{ omit if item.group is defined and item.group == item.username else (item.group if item.group is defined else (users_group if users_group else omit)) }}"
    groups: "{{ item.groups|join(',') if item.groups is defined else users_groups|join(',')}}"
    ssh_key_file: ".ssh/id_{{ item.ssh_key_type|default('rsa') }}"
    ssh_key_passphrase: "{{ item.ssh_key_password|default('') }}"
    ssh_key_bits: "{{ item.ssh_key_bits|default(2048) }}"
    createhome: "{{ item.home_create|default(omit) }}"
  with_items: users

- name: Setting user's home permission
  file:
    dest: "{{ item.home|default(users_home ~ '/' ~ item.username) }}"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    mode: "{{ item.home_mode if item.home_mode is defined else users_home_mode }}"
  when: item.home_create is not defined or item.home_create
  with_items: users
